from os import getenv
from dotenv import load_dotenv

load_dotenv()

SECRET_KEY = getenv("SECRET_KEY")
DB_NAME = getenv("DB_NAME")
DB_USERNAME = getenv("DB_USERNAME")
DB_PASSWORD = getenv("DB_PASSWORD")
DB_HOST = getenv("DB_HOST")
BOOTSTRAP_SERVE_LOCAL = getenv("BOOTSTRAP_SERVE_LOCAL")
OPENAI_API_KEY = getenv("OPENAI_API_KEY")
MAIL_SERVER = getenv("MAIL_SERVER")
MAIL_PORT = getenv("MAIL_PORT")
MAIL_USE_TLS = getenv("MAIL_USE_TLS")
MAIL_USERNAME = getenv("MAIL_USERNAME")
MAIL_PASSWORD = getenv("MAIL_PASSWORD")
MAIL_DEFAULT_SENDER = getenv("MAIL_DEFAULT_SENDER")
GOOGLE_CLIENT_ID=getenv("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET=getenv("GOOGLE_CLIENT_SECRET")